version: 2

sources:
  - name: raw
    tables:
      - name: sales
        identifier: raw_gz_sales
        columns:
          - name: date_order
          - name: order_id
          - name: product_id
          - name: total_revenue
          - name: quantity

      - name: product
        identifier: raw_gz_product
        columns:
          - name: product_id
          - name: product_name

      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: order_id
          - name: ship_date
